// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `describe`, `live`, `load_server`, `ms`, `need`, `on_rt`, `percentile`, `runtime`, `save_server`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Client`, `Live`, `Server`

/// Loads (or creates) the client identity and the paired server from `docs_dir`.
Future<String> initClient({required String docsDir}) =>
    RustLib.instance.api.crateApiSpikeInitClient(docsDir: docsDir);

/// Pairs with the agent from a `lanpilot://pair?d=...` URI. Returns a summary with the time taken.
Future<String> pair({required String uri}) =>
    RustLib.instance.api.crateApiSpikePair(uri: uri);

/// Connects to the paired agent and opens a session. Replaces any live session.
Future<String> connect() => RustLib.instance.api.crateApiSpikeConnect();

/// Traces a 200 px square with pointer datagrams: 4 sides x 30 steps, 8 ms apart.
Future<String> drawSquare() => RustLib.instance.api.crateApiSpikeDrawSquare();

/// Sends `rounds` RunCommand("ping") requests one at a time and reports the round trips.
Future<String> latencyTest({required int rounds}) =>
    RustLib.instance.api.crateApiSpikeLatencyTest(rounds: rounds);

/// Sends one UDP packet to `addr` ("ip:port"), which makes iOS show the local
/// network prompt (or fail if access was denied). The agent ignores it.
Future<String> probeLan({required String addr}) =>
    RustLib.instance.api.crateApiSpikeProbeLan(addr: addr);

/// Closes the live session, if any.
Future<String> disconnect() => RustLib.instance.api.crateApiSpikeDisconnect();
